  0%|                                                                                                            | 0/15630 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/lijinrun/lgs/Roberta-Llama-Mistral/training_script.py", line 270, in <module>
    main(args)
  File "/home/lijinrun/lgs/Roberta-Llama-Mistral/training_script.py", line 265, in main
    trainer.train()
  File "/home/lijinrun/anaconda3/envs/class2/lib/python3.11/site-packages/transformers/trainer.py", line 2171, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/lijinrun/anaconda3/envs/class2/lib/python3.11/site-packages/transformers/trainer.py", line 2531, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lijinrun/anaconda3/envs/class2/lib/python3.11/site-packages/transformers/trainer.py", line 3678, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_weighted_trainer.<locals>._WeightedBCELossTrainer.compute_loss() got an unexpected keyword argument 'num_items_in_batch'
